### ISSUE TITLE
docs generator does not publish to monax.io

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-keys.js#1]
- https://staging.monax.io/docs/documentation/keys.js/
- under **Version** the listed versions point to eris-cm and 404
- @NodeGuy are there stats on package usage? is it worth deprecating if not being used? As well, `eris-keys` is a dependency and marked for deprecation (moving into eris-db)

**Comment by NodeGuy** [comment]
I created it for our use so no, it should not be deprecated.
